default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: zxstore_development

test:
  <<: *default
  database: zxstore_test

production:
  <<: *default
  database: zxstore
